server:
  port: 8097
spring:
  application:
    name: portfolio-client
  security:
    oauth2:
      client:
        registration:
          crypto-portfolio:
              client-id: crypto-portfolio
              client-secret: 26gqNjOBrLrrJtpuuQ06GkeGkaxnBui9
              client-name: Crypto Potfolio
              redirect-uri: http://localhost:8097/login/oauth2/code/crypto-portfolio
              authorization-grant-type: authorization_code
              scope: openid
              provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/crypto-portfolio


